//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacial.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_empleado
    {
        public int Id_empleado { get; set; }
        public string Emple_nombre { get; set; }
        public string Emple_apellido { get; set; }
        public Nullable<int> Emple_DUI { get; set; }
        public string Emple_direccion { get; set; }
        public Nullable<int> Emple_tel { get; set; }
        public string Emple_email { get; set; }
        public string Emple_cargo { get; set; }
    }
}
